#ifndef ACE_CONFIG_H
#define ACE_CONFIG_H

#define ACE_DEFAULT_BACKLOG SOMAXCONN
#define ACE_DEFAULT_SELECT_REACTOR_SIZE 16384
#define ACE_DEFAULT_CDR_MEMCPY_TRADEOFF 1048576

#include <ace/config-linux.h>

#endif
